import 'package:pizzacorn_ui/src/form/phonefield.dart';

final List<CountryPhone> countriesData = [
  CountryPhone(name: "Afganistán", code: "AF", prefix: "93", flag: "🇦🇫"),
  CountryPhone(name: "Albania", code: "AL", prefix: "355", flag: "🇦🇱"),
  CountryPhone(name: "Alemania", code: "DE", prefix: "49", flag: "🇩🇪"),
  CountryPhone(name: "Andorra", code: "AD", prefix: "376", flag: "🇦🇩"),
  CountryPhone(name: "Angola", code: "AO", prefix: "244", flag: "🇦🇴"),
  CountryPhone(name: "Arabia Saudita", code: "SA", prefix: "966", flag: "🇸🇦"),
  CountryPhone(name: "Argelia", code: "DZ", prefix: "213", flag: "🇩🇿"),
  CountryPhone(name: "Argentina", code: "AR", prefix: "54", flag: "🇦🇷"),
  CountryPhone(name: "Armenia", code: "AM", prefix: "374", flag: "🇦🇲"),
  CountryPhone(name: "Australia", code: "AU", prefix: "61", flag: "🇦🇺"),
  CountryPhone(name: "Austria", code: "AT", prefix: "43", flag: "🇦🇦"),
  CountryPhone(name: "Azerbaiyán", code: "AZ", prefix: "994", flag: "🇦🇿"),
  CountryPhone(name: "Bahamas", code: "BS", prefix: "1", flag: "🇧🇸"),
  CountryPhone(name: "Bangladés", code: "BD", prefix: "880", flag: "🇧🇩"),
  CountryPhone(name: "Barbados", code: "BB", prefix: "1", flag: "🇧🇧"),
  CountryPhone(name: "Baréin", code: "BH", prefix: "973", flag: "🇧🇭"),
  CountryPhone(name: "Bélgica", code: "BE", prefix: "32", flag: "🇧🇪"),
  CountryPhone(name: "Belice", code: "BZ", prefix: "501", flag: "🇧🇿"),
  CountryPhone(name: "Benín", code: "BJ", prefix: "229", flag: "🇧🇯"),
  CountryPhone(name: "Bielorrusia", code: "BY", prefix: "375", flag: "🇧🇾"),
  CountryPhone(name: "Bolivia", code: "BO", prefix: "591", flag: "🇧🇴"),
  CountryPhone(name: "Bosnia y Herzegovina", code: "BA", prefix: "387", flag: "🇧🇦"),
  CountryPhone(name: "Botsuana", code: "BW", prefix: "267", flag: "🇧🇼"),
  CountryPhone(name: "Brasil", code: "BR", prefix: "55", flag: "🇧🇷"),
  CountryPhone(name: "Brunéi", code: "BN", prefix: "673", flag: "🇧🇳"),
  CountryPhone(name: "Bulgaria", code: "BG", prefix: "359", flag: "🇧🇬"),
  CountryPhone(name: "Burkina Faso", code: "BF", prefix: "226", flag: "🇧🇫"),
  CountryPhone(name: "Burundi", code: "BI", prefix: "257", flag: "🇧🇮"),
  CountryPhone(name: "Bután", code: "BT", prefix: "975", flag: "🇧🇹"),
  CountryPhone(name: "Cabo Verde", code: "CV", prefix: "238", flag: "🇨🇻"),
  CountryPhone(name: "Camboya", code: "KH", prefix: "855", flag: "🇰🇭"),
  CountryPhone(name: "Camerún", code: "CM", prefix: "237", flag: "🇨🇲"),
  CountryPhone(name: "Canadá", code: "CA", prefix: "1", flag: "🇨🇦"),
  CountryPhone(name: "Catar", code: "QA", prefix: "974", flag: "🇶🇦"),
  CountryPhone(name: "Chad", code: "TD", prefix: "235", flag: "🇹🇩"),
  CountryPhone(name: "Chile", code: "CL", prefix: "56", flag: "🇨🇱"),
  CountryPhone(name: "China", code: "CN", prefix: "86", flag: "🇨🇳"),
  CountryPhone(name: "Chipre", code: "CY", prefix: "357", flag: "🇨🇾"),
  CountryPhone(name: "Colombia", code: "CO", prefix: "57", flag: "🇨🇴"),
  CountryPhone(name: "Comoras", code: "KM", prefix: "269", flag: "🇰🇲"),
  CountryPhone(name: "Corea del Norte", code: "KP", prefix: "850", flag: "🇰🇵"),
  CountryPhone(name: "Corea del Sur", code: "KR", prefix: "82", flag: "🇰🇷"),
  CountryPhone(name: "Costa de Marfil", code: "CI", prefix: "225", flag: "🇨🇮"),
  CountryPhone(name: "Costa Rica", code: "CR", prefix: "506", flag: "🇨🇷"),
  CountryPhone(name: "Croacia", code: "HR", prefix: "385", flag: "🇭🇷"),
  CountryPhone(name: "Cuba", code: "CU", prefix: "53", flag: "🇨🇺"),
  CountryPhone(name: "Dinamarca", code: "DK", prefix: "45", flag: "🇩🇰"),
  CountryPhone(name: "Dominica", code: "DM", prefix: "1", flag: "🇩🇲"),
  CountryPhone(name: "Ecuador", code: "EC", prefix: "593", flag: "🇪🇨"),
  CountryPhone(name: "Egipto", code: "EG", prefix: "20", flag: "🇪🇬"),
  CountryPhone(name: "El Salvador", code: "SV", prefix: "503", flag: "🇸🇻"),
  CountryPhone(name: "Emiratos Árabes Unidos", code: "AE", prefix: "971", flag: "🇦🇪"),
  CountryPhone(name: "Eritrea", code: "ER", prefix: "291", flag: "🇪🇷"),
  CountryPhone(name: "Eslovaquia", code: "SK", prefix: "421", flag: "🇸🇰"),
  CountryPhone(name: "Eslovenia", code: "SI", prefix: "386", flag: "🇸🇮"),
  CountryPhone(name: "España", code: "ES", prefix: "34", flag: "🇪🇸"),
  CountryPhone(name: "Estados Unidos", code: "US", prefix: "1", flag: "🇺🇸"),
  CountryPhone(name: "Estonia", code: "EE", prefix: "372", flag: "🇪🇪"),
  CountryPhone(name: "Etiopía", code: "ET", prefix: "251", flag: "🇪🇹"),
  CountryPhone(name: "Filipinas", code: "PH", prefix: "63", flag: "🇵🇭"),
  CountryPhone(name: "Finlandia", code: "FI", prefix: "358", flag: "🇫🇮"),
  CountryPhone(name: "Fiyi", code: "FJ", prefix: "679", flag: "🇫🇯"),
  CountryPhone(name: "Francia", code: "FR", prefix: "33", flag: "🇫🇷"),
  CountryPhone(name: "Gabón", code: "GA", prefix: "241", flag: "🇬🇦"),
  CountryPhone(name: "Gambia", code: "GM", prefix: "220", flag: "🇬🇲"),
  CountryPhone(name: "Georgia", code: "GE", prefix: "995", flag: "🇬🇪"),
  CountryPhone(name: "Ghana", code: "GH", prefix: "233", flag: "🇬🇭"),
  CountryPhone(name: "Granada", code: "GD", prefix: "1", flag: "🇬🇩"),
  CountryPhone(name: "Grecia", code: "GR", prefix: "30", flag: "🇬🇷"),
  CountryPhone(name: "Guatemala", code: "GT", prefix: "502", flag: "🇬🇹"),
  CountryPhone(name: "Guyana", code: "GY", prefix: "592", flag: "🇬🇾"),
  CountryPhone(name: "Guinea", code: "GN", prefix: "224", flag: "🇬🇳"),
  CountryPhone(name: "Guinea-Bisáu", code: "GW", prefix: "245", flag: "🇬🇼"),
  CountryPhone(name: "Guinea Ecuatorial", code: "GQ", prefix: "240", flag: "🇬🇶"),
  CountryPhone(name: "Haití", code: "HT", prefix: "509", flag: "🇭🇹"),
  CountryPhone(name: "Honduras", code: "HN", prefix: "504", flag: "🇭🇳"),
  CountryPhone(name: "Hungría", code: "HU", prefix: "36", flag: "🇭🇺"),
  CountryPhone(name: "India", code: "IN", prefix: "91", flag: "🇮🇳"),
  CountryPhone(name: "Indonesia", code: "ID", prefix: "62", flag: "🇮🇩"),
  CountryPhone(name: "Irak", code: "IQ", prefix: "964", flag: "🇮🇶"),
  CountryPhone(name: "Irán", code: "IR", prefix: "98", flag: "🇮🇷"),
  CountryPhone(name: "Irlanda", code: "IE", prefix: "353", flag: "🇮🇪"),
  CountryPhone(name: "Islandia", code: "IS", prefix: "354", flag: "🇮🇸"),
  CountryPhone(name: "Islas Marshall", code: "MH", prefix: "692", flag: "🇲🇭"),
  CountryPhone(name: "Islas Salomón", code: "SB", prefix: "677", flag: "🇸🇧"),
  CountryPhone(name: "Israel", code: "IL", prefix: "972", flag: "🇮🇱"),
  CountryPhone(name: "Italia", code: "IT", prefix: "39", flag: "🇮🇹"),
  CountryPhone(name: "Jamaica", code: "JM", prefix: "1", flag: "🇯🇲"),
  CountryPhone(name: "Japón", code: "JP", prefix: "81", flag: "🇯🇵"),
  CountryPhone(name: "Jordania", code: "JO", prefix: "962", flag: "🇯🇴"),
  CountryPhone(name: "Kazajistán", code: "KZ", prefix: "7", flag: "🇰🇿"),
  CountryPhone(name: "Kenia", code: "KE", prefix: "254", flag: "🇰🇪"),
  CountryPhone(name: "Kirguistán", code: "KG", prefix: "996", flag: "🇰🇬"),
  CountryPhone(name: "Kiribati", code: "KI", prefix: "686", flag: "🇰🇮"),
  CountryPhone(name: "Kuwait", code: "KW", prefix: "965", flag: "🇰🇼"),
  CountryPhone(name: "Laos", code: "LA", prefix: "856", flag: "🇱🇦"),
  CountryPhone(name: "Lesoto", code: "LS", prefix: "266", flag: "🇱🇸"),
  CountryPhone(name: "Letonia", code: "LV", prefix: "371", flag: "🇱🇻"),
  CountryPhone(name: "Líbano", code: "LB", prefix: "961", flag: "🇱🇧"),
  CountryPhone(name: "Liberia", code: "LR", prefix: "231", flag: "🇱🇷"),
  CountryPhone(name: "Libia", code: "LY", prefix: "218", flag: "🇱🇾"),
  CountryPhone(name: "Liechtenstein", code: "LI", prefix: "423", flag: "🇱🇮"),
  CountryPhone(name: "Lituania", code: "LT", prefix: "370", flag: "🇱🇹"),
  CountryPhone(name: "Luxemburgo", code: "LU", prefix: "352", flag: "🇱🇺"),
  CountryPhone(name: "Macedonia del Norte", code: "MK", prefix: "389", flag: "🇲🇰"),
  CountryPhone(name: "Madagascar", code: "MG", prefix: "261", flag: "🇲🇬"),
  CountryPhone(name: "Malasia", code: "MY", prefix: "60", flag: "🇲🇾"),
  CountryPhone(name: "Malaui", code: "MW", prefix: "265", flag: "🇲🇼"),
  CountryPhone(name: "Maldivas", code: "MV", prefix: "960", flag: "🇲🇻"),
  CountryPhone(name: "Malí", code: "ML", prefix: "223", flag: "🇲🇱"),
  CountryPhone(name: "Malta", code: "MT", prefix: "356", flag: "🇲🇹"),
  CountryPhone(name: "Marruecos", code: "MA", prefix: "212", flag: "🇲🇦"),
  CountryPhone(name: "Mauricio", code: "MU", prefix: "230", flag: "🇲🇺"),
  CountryPhone(name: "Mauritania", code: "MR", prefix: "222", flag: "🇲🇷"),
  CountryPhone(name: "México", code: "MX", prefix: "52", flag: "🇲🇽"),
  CountryPhone(name: "Micronesia", code: "FM", prefix: "691", flag: "🇫🇲"),
  CountryPhone(name: "Moldavia", code: "MD", prefix: "373", flag: "🇲🇩"),
  CountryPhone(name: "Mónaco", code: "MC", prefix: "377", flag: "🇲🇨"),
  CountryPhone(name: "Mongolia", code: "MN", prefix: "976", flag: "🇲🇳"),
  CountryPhone(name: "Montenegro", code: "ME", prefix: "382", flag: "🇲🇪"),
  CountryPhone(name: "Mozambique", code: "MZ", prefix: "258", flag: "🇲🇿"),
  CountryPhone(name: "Namibia", code: "NA", prefix: "264", flag: "🇳🇦"),
  CountryPhone(name: "Nauru", code: "NR", prefix: "674", flag: "🇳🇷"),
  CountryPhone(name: "Nepal", code: "NP", prefix: "977", flag: "🇳🇵"),
  CountryPhone(name: "Nicaragua", code: "NI", prefix: "505", flag: "🇳🇮"),
  CountryPhone(name: "Níger", code: "NE", prefix: "227", flag: "🇳🇪"),
  CountryPhone(name: "Nigeria", code: "NG", prefix: "234", flag: "🇳🇬"),
  CountryPhone(name: "Noruega", code: "NO", prefix: "47", flag: "🇳🇴"),
  CountryPhone(name: "Nueva Zelanda", code: "NZ", prefix: "64", flag: "🇳🇿"),
  CountryPhone(name: "Omán", code: "OM", prefix: "968", flag: "🇴🇲"),
  CountryPhone(name: "Países Bajos", code: "NL", prefix: "31", flag: "🇳🇱"),
  CountryPhone(name: "Pakistán", code: "PK", prefix: "92", flag: "🇵🇰"),
  CountryPhone(name: "Palaos", code: "PW", prefix: "680", flag: "🇵🇼"),
  CountryPhone(name: "Panamá", code: "PA", prefix: "507", flag: "🇵🇦"),
  CountryPhone(name: "Papúa Nueva Guinea", code: "PG", prefix: "675", flag: "🇵🇬"),
  CountryPhone(name: "Paraguay", code: "PY", prefix: "595", flag: "🇵🇾"),
  CountryPhone(name: "Perú", code: "PE", prefix: "51", flag: "🇵🇪"),
  CountryPhone(name: "Polonia", code: "PL", prefix: "48", flag: "🇵🇱"),
  CountryPhone(name: "Portugal", code: "PT", prefix: "351", flag: "🇵🇹"),
  CountryPhone(name: "Reino Unido", code: "GB", prefix: "44", flag: "🇬🇧"),
  CountryPhone(name: "República Centroafricana", code: "CF", prefix: "236", flag: "🇨🇫"),
  CountryPhone(name: "República Checa", code: "CZ", prefix: "420", flag: "🇨🇿"),
  CountryPhone(name: "República del Congo", code: "CG", prefix: "242", flag: "🇨🇬"),
  CountryPhone(name: "República Democrática del Congo", code: "CD", prefix: "243", flag: "🇨🇩"),
  CountryPhone(name: "República Dominicana", code: "DO", prefix: "1", flag: "🇩🇴"),
  CountryPhone(name: "Ruanda", code: "RW", prefix: "250", flag: "🇷🇼"),
  CountryPhone(name: "Rumania", code: "RO", prefix: "40", flag: "🇷🇴"),
  CountryPhone(name: "Rusia", code: "RU", prefix: "7", flag: "🇷🇺"),
  CountryPhone(name: "Samoa", code: "WS", prefix: "685", flag: "🇼🇸"),
  CountryPhone(name: "San Cristóbal y Nieves", code: "KN", prefix: "1", flag: "🇰🇳"),
  CountryPhone(name: "San Marino", code: "SM", prefix: "378", flag: "🇸🇲"),
  CountryPhone(name: "San Vicente y las Granadinas", code: "VC", prefix: "1", flag: "🇻🇨"),
  CountryPhone(name: "Santa Lucía", code: "LC", prefix: "1", flag: "🇱🇨"),
  CountryPhone(name: "Santo Tomé y Príncipe", code: "ST", prefix: "239", flag: "🇸🇹"),
  CountryPhone(name: "Senegal", code: "SN", prefix: "221", flag: "🇸🇳"),
  CountryPhone(name: "Serbia", code: "RS", prefix: "381", flag: "🇷🇸"),
  CountryPhone(name: "Seychelles", code: "SC", prefix: "248", flag: "🇸🇨"),
  CountryPhone(name: "Sierra Leona", code: "SL", prefix: "232", flag: "🇸🇱"),
  CountryPhone(name: "Singapur", code: "SG", prefix: "65", flag: "🇸🇬"),
  CountryPhone(name: "Siria", code: "SY", prefix: "963", flag: "🇸🇾"),
  CountryPhone(name: "Somalia", code: "SO", prefix: "252", flag: "🇸🇴"),
  CountryPhone(name: "Sri Lanka", code: "LK", prefix: "94", flag: "🇱🇰"),
  CountryPhone(name: "Sudáfrica", code: "ZA", prefix: "27", flag: "🇿🇦"),
  CountryPhone(name: "Sudán", code: "SD", prefix: "249", flag: "🇸🇩"),
  CountryPhone(name: "Sudán del Sur", code: "SS", prefix: "211", flag: "🇸🇸"),
  CountryPhone(name: "Suecia", code: "SE", prefix: "46", flag: "🇸🇪"),
  CountryPhone(name: "Suiza", code: "CH", prefix: "41", flag: "🇨🇭"),
  CountryPhone(name: "Surinam", code: "SR", prefix: "597", flag: "🇸🇷"),
  CountryPhone(name: "Tailandia", code: "TH", prefix: "66", flag: "🇹🇭"),
  CountryPhone(name: "Taiwán", code: "TW", prefix: "886", flag: "🇹🇼"),
  CountryPhone(name: "Tanzania", code: "TZ", prefix: "255", flag: "🇹🇿"),
  CountryPhone(name: "Tayikistán", code: "TJ", prefix: "992", flag: "🇹🇯"),
  CountryPhone(name: "Timor Oriental", code: "TL", prefix: "670", flag: "🇹🇱"),
  CountryPhone(name: "Togo", code: "TG", prefix: "228", flag: "🇹🇬"),
  CountryPhone(name: "Tonga", code: "TO", prefix: "676", flag: "🇹🇴"),
  CountryPhone(name: "Trinidad y Tobago", code: "TT", prefix: "1", flag: "🇹🇹"),
  CountryPhone(name: "Túnez", code: "TN", prefix: "216", flag: "🇹🇳"),
  CountryPhone(name: "Turkmenistán", code: "TM", prefix: "993", flag: "🇹🇲"),
  CountryPhone(name: "Turquía", code: "TR", prefix: "90", flag: "🇹🇷"),
  CountryPhone(name: "Tuvalu", code: "TV", prefix: "688", flag: "🇹🇻"),
  CountryPhone(name: "Ucrania", code: "UA", prefix: "380", flag: "🇺🇦"),
  CountryPhone(name: "Uganda", code: "UG", prefix: "256", flag: "🇺🇬"),
  CountryPhone(name: "Uruguay", code: "UY", prefix: "598", flag: "🇺🇾"),
  CountryPhone(name: "Uzbekistán", code: "UZ", prefix: "998", flag: "🇺🇿"),
  CountryPhone(name: "Vanuatu", code: "VU", prefix: "678", flag: "🇻🇺"),
  CountryPhone(name: "Venezuela", code: "VE", prefix: "58", flag: "🇻🇪"),
  CountryPhone(name: "Vietnam", code: "VN", prefix: "84", flag: "🇻🇳"),
  CountryPhone(name: "Yemen", code: "YE", prefix: "967", flag: "🇾🇪"),
  CountryPhone(name: "Yibuti", code: "DJ", prefix: "253", flag: "🇩🇯"),
  CountryPhone(name: "Zambia", code: "ZM", prefix: "260", flag: "🇿🇲"),
  CountryPhone(name: "Zimbabue", code: "ZW", prefix: "263", flag: "🇿🇼"),
];